version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
      - npm list # List installed packages for debugging
  
  pre_build:
    commands:
      - echo Checking project structure...
      - ls -la
      - echo Checking Angular configuration...
      - cat angular.json || echo "angular.json not found"
  
  build:
    commands:
      - echo Building the Angular application...
      - ng version # Check Angular version
      - ng build --configuration production || ng build --prod
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Checking build output...
      - ls -la dist/ || echo "dist/ directory not found"
      - ls -la dist/my-angular-project || echo "dist/my-angular-project directory not found"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/my-angular-project'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
