version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # You can use 14, 16, or 18 depending on your Angular version
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
  
  build:
    commands:
      - echo Building the Angular application...
      - ng build --configuration production
      # If you're using an older version of Angular, you might need to use this instead:
      # - ng build --prod
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/my-angular-project'  # This is your actual project name
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
